[package]
name = "sif-kdtree"
description = "simple, immutable, flat K-D tree"
version = "0.1.0"
edition = "2018"

[dependencies]
rayon = { version = "1.7", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }

[dev-dependencies]
proptest = "1.1"
