on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - uses: dtolnay/rust-toolchain@stable
    - run: cargo test --all-features
